name: Github Pages from branch

on:
  push:
    branches:
      - main # set your branch name to trigger deployment, usually it is main or master by default. 

permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' # node.js version, other versions not tested
      - name: Install Node dependencies
        run: npm install
      - name: Build site via jekyll/builder
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && JEKYLL_ENV=production jekyll build"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # set your publish dir, _site is jekyll default
